# Principal Component Analysis

In this notebook I will demonstrate my understanding of Principal Component Analysis (PCA) as a tool to reduce the number of dimensions in a dataset typically used for machine learning. I show my understanding of PCA by applying PCA usage as demonstrated in the chapter on PCA in the Python Data Science Handbook, on the Iris dataset. My purpose is to reduce the 4 dimensional Iris dataset to a two dimensional dataset using scikit-learn's PCA implementation.

## 1. load iris data

In [11]:
# your code goes here

,ID,small,medium,large,2.legs,4.legs,hair,hooves,mane,feathers,hunt,run,fly,swim
0,Dove,1.0,0,0,1,0,0,0,0,1,0,0,1,0
1,Hen,1.0,0,0,1,0,0,0,0,1,0,0,0,0
2,Duck,1.0,0,0,1,0,0,0,0,1,0,0,0,1
3,Goose,1.0,0,0,1,0,0,0,0,1,0,0,1,1
4,Owl,1.0,0,0,1,0,0,0,0,1,1,0,1,0
5,Hawk,1.0,0,0,1,0,0,0,0,1,1,0,1,0
6,Eagle,0.0,1,0,1,0,0,0,0,1,1,0,1,0
7,Fox,0.0,1,0,0,1,1,0,0,0,1,0,0,0
8,Dog,0.0,1,0,0,1,1,0,0,0,0,1,0,0
9,Wolf,0.0,1,0,0,1,1,0,1,0,1,1,0,0
10,Cat,1.0,0,0,0,1,1,0,0,0,1,0,0,0
11,Tiger,0.0,0,1,0,1,1,0,0,0,1,1,0,0
12,Lion,0.0,0,1,0,1,1,0,1,0,1,1,0,0
13,Horse,0.0,0,1,0,1,1,1,1,0,0,1,0,0
14,Zebra,0.0,0,1,0,1,1,1,1,0,0,1,0,0
15,Cow,0.0,0,1,0,1,1,1,0,0,0,0,0,0

## 2. import, configure and fit PCA

[your comment goes here]

In [ ]:
# your code goes here

## 3. visualize results
Below I have visualized the three iris types using three different colors in a scatter plot, with the two pricipal components on x and y axis.

[your comment goes here]

In [ ]:
# your code goes here

## 4. classify the reduced data set to the 3 iris type

[You can skip this part of the exercise if it takes too long. You can choose your own classifier. Determine the accuracy of your model. How does it compare to the classifier you previously used on all 4 dimensions?]

In [ ]:
# your code goes here